runcmd:
  - docker pull livepeer/comfystream:latest
  - mkdir -p ~/models/ComfyUI--models ~/models/ComfyUI--output
  - docker run --restart unless-stopped --stop-timeout 300 --gpus all --name comfystream -v ${HOME}/models/ComfyUI--models:/workspace/ComfyUI/models -v ${HOME}/models/ComfyUI--output:/workspace/ComfyUI/output -p 3000:3000 -p 8889:8889 livepeer/comfystream:latest --download-models --build-engines
